plugins { id 'com.android.application' }

android {
    namespace 'com.korvalune.game'
    compileSdk 34
    defaultConfig {
        applicationId 'com.korvalune.game'
        minSdk 26
        targetSdk 34
        versionCode 1011
        versionName '1.10.11'
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
